name: "turn_off"
version: "1.0.0"
slug: "turn_off"
description: "turn_off_gpio17"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
devices:
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"
options: {}
schema: {}
