name: "turn_on"
version: "1.0.0"
slug: "turn_on"
description: "turn_on_gpio17"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
devices:
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"
options: {}
schema: {}
