name: "test_select"
version: "1.0"
slug: "test_select_options"
description: "An add-on to test select and options features."
arch:
  - "armhf"
  - "armv7"
  - "aarch64"
  - "amd64"
  - "i386"
startup: "application"
boot: "auto"
options:
  mode: default
schema:
  mode:
    type: list(default|aurora|cobalt2)?
