name: "GPIO Control Add-on"
version: "1.0.0"
slug: "gpio_control"
description: "Control GPIO pins on Raspberry Pi 5."
arch:
  - armhf
  - armv7
  - aarch64
startup: application
boot: manual
options:
  pins: 
  state: "off"
schema:
  pins: list?
  state: str?
devices:
   - "/dev/gpiochip0:/dev/gpiochip0:rwm"

