name: enviroment_sensors
version: dev
slug: enviroment_sensors
description: "Environment indicators collection"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - temperture
  - humidity
  - oxygen-concentration
  - pressure
options:
  addr-bmp: none
  addr-sht: none
  addr-oxy: none
  api_base_url:
    required: true
  api_token:
    required: true
  ssl: false
  temperture: false
  humidity: false
  oxygen-concentration: false
  pressure: false
schema:
  api_base_url: str?
  api_token: str?
  tempurture: bool
  humidity: bool
  oxygen-concentration: bool
  pressure: bool
devices:
  - "/dev/i2c-5:rwm"

