name: select
version: dev
slug: select
description: "test select"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - bmp180
  - bmp280
  - sht31
  - sht45
  - oxygen
options:
  addr-bmp: none
  addr-sht: none
  addr-oxy: none
schema:
  ssl: bool
  bmp180: bool
  bmp280: bool
  sht31: bool
  sht45: bool
  oxygen: bool
  addr-bmp: list(none|0x76|0x77)
  addr-sht: list(none|0x44|0x45)
  addr-oxy: list(none|0x70|0x71|0x72|0x73)

