name: select
version: dev
slug: select
description: "test select"
arch:
  - aarch64
  - amd64
  - armv7
options:
  theme: default
  sensor: sr
schema:
  theme: list(default|aurora|cobalt2|dark|dracula|espresso-libre|github-dark|github-dark-default|github-dark-dimmed)
  sensor: list(sr|bmp180|bmp280|sht31|sht45|Oxygen)
