name: select
version: dev
slug: select
description: "test select"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - bmp180
  - bmp280
  - sht31
  - sht45
  - oxygen
options:
  addr-bmp: none
schema:
  addr-bmp: list(none|0x76|0x77)
  ssl: bool
  bmp180: bool
  bmp280: bool
  sht31: bool
  sht45: bool
  oxygen: bool

