name: select
version: dev
slug: select
description: "test select"
arch:
  - aarch64
  - amd64
  - armv7
map:
  bmp180
options:
  theme: default
schema:
  theme: list(default|aurora|cobalt2|dark|dracula|espresso-libre|github-dark|github-dark-default|github-dark-dimmed)
  bmp180: bool

