name: select
version: dev
slug: select
description: "test select"
arch:
  - aarch64
  - amd64
  - armv7

schema:
  theme:
    type: map
    name: "Select Themes"
    description: "Enable or disable themes"
    mapping:
      default:
        type: boolean
        name: "Default theme"
        description: "Enable the default theme"
        default: true
      aurora:
        type: boolean
        default: false
      cobalt2:
        type: boolean
        default: false
      dark:
        type: boolean
        default: false
      dracula:
        type: boolean
        default: false
      espresso-libre:
        type: boolean
        default: false
      github-dark:
        type: boolean
        default: false
      github-dark-default:
        type: boolean
        default: false
      github-dark-dimmed:
        type: boolean
        default: false

  sensor:
    type: map
    name: "Select Sensors"
    description: "Enable or disable sensors"
    mapping:
      sr:
        type: boolean
        default: true
      bmp180:
        type: boolean
        default: false
      bmp280:
        type: boolean
        default: false
      sht31:
        type: boolean
        default: false
      sht45:
        type: boolean
        default: false
      Oxygen:
        type: boolean
        default: false

