name: "addons"
version: "1.0.0"
slug: "addon"
description: "Control GPIO pins using lgpio"
arch:
  - armv7
  - arm64
  - amd64
startup: "application"
boot: "auto"

options: {}
schema: {}

host_network: true  # Sử dụng mạng của host, nếu cần.

privileged:
  - SYS_RAWIO  # Cho phép truy cập vào phần cứng.
  - DAC_OVERRIDE  # Bỏ qua các giới hạn DAC nếu cần thiết.

devices:
  - "/dev:/dev:rwm"  # Gắn toàn bộ thư mục /dev từ host vào container.

environment: []

