---
name: addons
version: 1.0.0
slug: addon
description: Control GPIO pins using lgpio
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options: {}
schema: {}
host_network: true
privileged:
  - SYS_RAWIO
  - DAC_OVERRIDE
devices:
  - /dev:/dev:rwm
environment: []

