name: "automation"
version: "1.0.0"
slug: "auto"
description: "Ethan"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
devices:
  - "/dev/i2c-1:/dev/i2c-1:rwm"
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"
options: {}
schema: {}
